name: Style and Format Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          exclude: \.(svg|pyc)$
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HorstBaerbel/action-clang-format@1.5
